# Generated by Django 5.2.5 on 2025-10-15 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(blank=True, max_length=100, null=True)),
                ('familiyasi', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=100, null=True)),
                ('tugilgan_sana', models.DateField(blank=True, null=True)),
                ('yil', models.IntegerField(blank=True, null=True)),
                ('manzil', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
