# Generated by Django 5.2.5 on 2025-10-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akkount', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=100),
        ),
    ]
