# Generated by Django 5.2.5 on 2025-10-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='new_column',
        ),
    ]
