# Generated by Django 5.2.5 on 2025-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_news_new_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='joylash',
            field=models.CharField(choices=[('car', 'Carouselga'), ('right', 'Right'), ('feat', 'Featured'), ('lat', 'Latest'), ('tran', 'Tranding')], max_length=255),
        ),
    ]
