# Generated by Django 5.2.5 on 2025-10-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sana',
            field=models.DateField(),
        ),
    ]
