# Generated by Django 5.2.5 on 2025-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_product_category_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
