# Generated by Django 5.2.5 on 2025-10-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_news_new_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_count',
            new_name='view_count',
        ),
    ]
